## Preprocessing

In [ ]:
            # Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("./drive/MyDrive/charity_data.csv")
application_df.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(["EIN", "NAME"], 1)

In [ ]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE

application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE

application_counts = application_df["APPLICATION_TYPE"].value_counts()

application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [16]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE

application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [17]:
application_types_to_replace = list(application_counts[application_counts < 500].index)

In [18]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [19]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE

class_counts = application_df["CLASSIFICATION"].value_counts()

class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1580        1
C1900        1
C1732        1
C6100        1
C3700        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [20]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

class_counts[class_counts>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C2400        6
C4100        6
C1600        5
C1257        5
C0           3
C2710        3
C1260        3
C1267        2
C1234        2
C1246        2
C1256        2
C3200        2
Name: CLASSIFICATION, dtype: int64

In [22]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE

classification_to_replace = list (class_counts[class_counts>1])

# Replace in dataframe
for cls in classification_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1580        1
C1900        1
C1732        1
C6100        1
C3700        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [23]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df

       STATUS   ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0           1      5000  ...                         1                         0
1           1    108590  ...                         1                         0
2           1      5000  ...                         1                         0
3           1      6692  ...                         1                         0
4           1    142590  ...                         1                         0
...       ...       ...  ...                       ...                       ...
34294       1      5000  ...                         1                         0
34295       1      5000  ...                         1                         0
34296       1      5000  ...                         1                         0
34297       1      5000  ...                         1                         0
34298       1  36500179  ...                         1                         0

[34299 rows x 109 columns]

In [24]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE

X = application_with_dummies_df.drop(["IS_SUCCESSFUL"], axis="columns").values
y = application_with_dummies_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [25]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [26]:
number_input_features = len(X_train[0])
number_input_features

108

In [27]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

number_input_features = len(X_train[0])
#number_input_features
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30


nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units= hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu")
)

# Output layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=1, activation="sigmoid")
)

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                8720

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 11,181
Trainable params: 11,181
Non-trainable params: 0
_________________________________________________________________

In [28]:
# Compile the model
#  YOUR CODE GOES HERE

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics= ["accuracy"])

In [29]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5752 - accuracy: 0.7212
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5551 - accuracy: 0.7298
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5516 - accuracy: 0.7301
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7307
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7313
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7328
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7313
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7325
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7338
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7332
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7336
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7348
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7336
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7352
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7354
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7371
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7369
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7356
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7370
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7365
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7380
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7373
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7377
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7371
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7385
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7386
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7391
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7399
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7400
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7382
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7386
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7396
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7385
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7393
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7390
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7396
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7399
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7398
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7406
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7402
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7408
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7407
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7400
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7414
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7404
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7393
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7405
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7400
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7412
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7413
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5316 - accuracy: 0.7420
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7413
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5311 - accuracy: 0.7408
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5315 - accuracy: 0.7408
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7400
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7406
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7404
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7412
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7425
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7418
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7421
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7404
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7424
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7412
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7412
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7407
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7419
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7409
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5299 - accuracy: 0.7416
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7413
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7411
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7410
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7413
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7414
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5290 - accuracy: 0.7419
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7418
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7420
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7416
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5300 - accuracy: 0.7419
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7423
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7412
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7413
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5288 - accuracy: 0.7421
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5288 - accuracy: 0.7422
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5291 - accuracy: 0.7414
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7419
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5288 - accuracy: 0.7420
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5286 - accuracy: 0.7420
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7414
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7424
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5281 - accuracy: 0.7418
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5282 - accuracy: 0.7418
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7424
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7421
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7409
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5283 - accuracy: 0.7424
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5282 - accuracy: 0.7425
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7423
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5277 - accuracy: 0.7422

In [30]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5694 - accuracy: 0.7297 - 418ms/epoch - 2ms/step
Loss: 0.5693509578704834, Accuracy: 0.72967928647995

In [31]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity.h5")